# Generated by Django 5.0.6 on 2024-05-29 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_content_textcontent_lesson_content_lesson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="slug",
        ),
    ]
