# Generated by Django 5.0.6 on 2024-05-31 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_assignment_grade_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="assignment_type",
            field=models.CharField(
                choices=[("quiz", "Quiz Assignment/Submission")], max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.student"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_type",
            field=models.CharField(
                choices=[("quiz", "Quiz Assignment/Submission")], max_length=50
            ),
        ),
    ]
